export const GET_CART_FAIL = "GET_CART_FAIL";
export const GET_CART_LOAD = "GET_CART_LOAD ";
export const GET_CART_SUCESS = "GET_CART_SUCESS";
export const ADD_CART_SUCESS = "ADD_CART_SUCESS";
export const ADD_CART_FAIL = "ADD_CART_FAIL";
export const DELETE_CART_SUCESS = "DELETE_CART_SUCESS";
export const DELETE_CART_FAIL = "DELETE_CART_FAIL";
