export const GET_COMMENT_FAIL = "GET_COMMENT_FAIL";
export const GET_COMMENT_LOAD = "GET_COMMENT_LOAD ";
export const GET_COMMENT_SUCESS = "GET_COMMENT_SUCESS";
export const ADD_COMMENT_SUCESS = "ADD_COMMENT_SUCESS";
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL";
