export const ORDERS_LOADING = "ORDERS_LOADING";
export const GET_ORDERS = "GET_ORDERS";
export const GET_ORDERS_LOAD = "GET_ORDERS_LOAD";
export const GET_ORDERS_FAIL = "GET_ORDERS_FAIL";
export const GET_ORDERS_SUCESS = "GET_ORDERS_SUCESS";
export const DELETE_ORDER_SUCESS = "DELETE_ORDER_SUCESS";
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";
export const CHECKOUT = "CHECKOUT";
