export const GET_PRODUCTS_LOAD = "GET_PRODUCTS_LOAD";
export const GET_PRODUCTS_SUCESS = "GET_PRODUCTS_SUCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";

export const DELETE_PRODUCT_SUCESS = "DELETE_PRODUCT_SUCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const GET_PRODUCT_LOAD = "GET_PRODUCT_LOAD";
export const GET_PRODUCT_SUCESS = "GET_PRODUCT_SUCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAILD";

export const TOGGLE_TRUE = "TOGGLE_TRUE";
export const TOGGLE_FALSE = "TOGGLE_FALSE";

export const EDIT_PRODUCT_SUCESS = "EDIT_PRODUCT_SUCESS";
export const EDIT_PRODUCT_FAIL = "EDIT_PRODUCT_FAIL";
